apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config-svc
spec:
  gateways:
    - {{ include "scp.ingress.gateway" . }}
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /configuration
      name: configuration
      rewrite:
        uri: /
      route:
        - destination:
            host: configuration
            port:
              number: 8080
